spring:
  application:
    name: master-docker-base-microservice
  data:
    redis:
      host: localhost
      port: 6379
logging:
  level:
    root: debug
management:
  endpoints:
    web:
      exposure:
        include: health, info, beans, metrics, threaddump, mappings, prometheus
  endpoint:
    health:
      enabled: true
      show-components: always
      show-details: always
    prometheus:
      enabled: true
server:
  port: 8080